services:
  chatflux-postgres-dev:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp123
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: